config/routes.rb
Rails.application.routes.draw do
  devise_for :users, except: %w[sessions#new sessions#create sessions#destroy], controllers: {sessions: "sessions"}
  mount Sidekiq::Web => '/sidekiq'
  root to: 'home#index'
  namespace :synchronizers do
    resources :products_synchronizer, only: %i[index]
    resources :orders_synchronizer, only: %i[index]
    resources :users_synchronizer, only: %i[index]
  end

  namespace :webhooks do
    get '/invoices', to: 'invoices#index'
  end

  namespace :customers do
    resources :sessions
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center mb-5">
        <h2 class="heading-section">Table #05</h2>
      </div>

      <div class="col-md-6 text-center mb-5">
        <h2 class="heading-section"><%= link_to 'Sign out', destroy_user_session_path%></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="table-wrap">
          <table class="table table-responsive-xl">
            <thead>
              <tr>
                <th>Đồng bộ hoá đơn từ KiotViet đến Flexzen</th>
                <th>Đồng bộ hàng hoá từ KiotViet đến Flexzen</th>
                <th>Đồng bộ khách hàng từ KiotViet đến Flexzen</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <%= link_to 'Đòng bộ hoá đơn', synchronizers_orders_synchronizer_index_path, class: 'btn btn-primary', :data => {:id => 'loading_gif'} %>
                </td>

                <td>
                  <%= link_to 'Đòng bộ hàng hoá', synchronizers_products_synchronizer_index_path, class: 'btn btn-secondary', :data => {:id => 'loading_gif'} %>
                </td>

                <td>
                  <%= link_to 'Đòng bộ khách hàng', synchronizers_users_synchronizer_index_path, class: 'btn btn-success', :data => {:id => 'loading_gif'} %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>